function data = read_dispersion_data(filename)
    % Function to read data from a file, ignoring the first 5 header lines
    % File is generated by the GDM52 family of codes. 

    % Open the file for reading
    fid = fopen(filename, 'r');
    
    % Check if file exists and opened successfully
    if fid == -1
        error('File could not be opened. Check the file path.');
    end
    
    % Skip the first 5 header lines
    for i = 1:5
        fgetl(fid);
    end
    
    % Read the remaining data into an array
    data = fscanf(fid, '%f', [7, Inf])';  % Adjust columns (7) based on the data structure
    
    % Close the file
    fclose(fid);
end